### ISSUE TITLE
maven-assembly-plugin broke ico file

### ISSUE THREAD

**Issue by lanmaster** [mvysny/vaadin14-embedded-jetty#4]
Hello! I make some modification:
```
@Route("")
public class MainView extends VerticalLayout implements PageConfigurator {
    public MainView() {
        Button button = new Button("Click me",
                event -> Notification.show("Clicked!"));
        add(button);
    }
    @Override
    public void configurePage(InitialPageSettings settings) {
        settings.addFavIcon("icon", "favicon.ico", "16x16");
    }
}
```

After clean+package there is broken ico file in result.
It is not actually this repo issue, but how we can fix maven-assembly-plugin to make them didn't broke ICO ?

**Comment by mvysny** [comment]
True, it would be good to demo the possibility to serve static content from the .jar.

**Comment by mvysny** [comment]
Just tried it out. Simply place any files into the `src/main/webapp/` folder; static files from that folder will be properly served by Jetty, both in development (when running from IDE) and from production (when running via `java -jar`). So, just place `favicon.ico` file into `src/main/webapp/` and it should work properly; to try it out just run `wget http://localhost:8080/favicon.ico`.

However the favicon will be ignored by the browser since the app is using the `@PWA` annotation and configures favicons in a different manner. Try to remove `@PWA` or use `@PWA(iconPath)`.

**Comment by lanmaster** [comment]
Sorry, i have not clearly enough expressed. I think there is a bug or feature in maven-assembly-plugin, is case it work with binary files. Examples: [https://github.com/Alfresco/alfresco-sdk/issues/468](https://github.com/Alfresco/alfresco-sdk/issues/468), [https://github.com/Alfresco/alfresco-sdk/issues/430](https://github.com/Alfresco/alfresco-sdk/issues/430). Most binary files like 'png' working correctly, but 'ico' is not. Maybe it is my local problem only, i m confused.
Steps to reproduce:
- put favicon.ico file in folder `src/main/webapp`
- make `clean` and `package` Maven steps
- inside JAR in folder `webapp` i found `favicon.ico` file with different size than source file and it looks like bug in pic viewer.
[favicon_src.zip](https://github.com/mvysny/vaadin14-embedded-jetty/files/3823058/favicon_src.zip)
[favicon_in_jar.zip](https://github.com/mvysny/vaadin14-embedded-jetty/files/3823059/favicon_in_jar.zip)

**Comment by lanmaster** [comment]
I found that problem somewhere in maven-resources-plugin or deeper. Please close issue.

**Comment by mvysny** [comment]
I see, now I understand, thank you. This looks like Maven is processing the resources in some weird way. There are the following lines in the pom.xml:

```
            <resource>
                <directory>src/main</directory>
                <filtering>true</filtering>
            </resource>
```

Let me try to set filtering to false.

**Comment by lanmaster** [comment]
> 
> 
> I see, now I understand, thank you. This looks like Maven is processing the resources in some weird way. There are the following lines in the pom.xml:
> 
> ```
>             <resource>
>                 <directory>src/main</directory>
>                 <filtering>true</filtering>
>             </resource>
> ```
> 
> Let me try to set filtering to false.

I tried it. Thanks! It work! ICO file is not broken now!

**Comment by mvysny** [comment]
Yup, setting filtering to false helped. I'll set it to false by default since we don't need filtering.
