### ISSUE TITLE
Assembly plugin and dependencies

### ISSUE THREAD

**Issue by lanmaster** [mvysny/vaadin14-embedded-jetty#5]
May be it would be useful to change assembly plugin to dependency plugin that could export all dependency jars to directory `libs/` ? Not all dependencies can healthy be unpack to one place. Sometimes `Spring framework` libs break down, for example.

**Comment by lanmaster** [comment]
If you comment out plugin section for `maven-assembly-plugin`  and add two others plugins:

```
            <!--
            1. Unpack webcomponents resources (is it enough?) to include in JAR later
            2. Dependency JARs copying to 'libs' directory
            -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-dependency-plugin</artifactId>
                <executions>

                    <execution>
                        <id>get-dependencies</id>
                        <phase>prepare-package</phase>
                        <goals>
                            <goal>unpack-dependencies</goal>
                        </goals>
                        <configuration>
                            <includes>
                                META-INF/resources/**/*,
                                META-INF/services/**/*
                            </includes>
                            <outputDirectory>target/classes/</outputDirectory>
                            <overWriteReleases>false</overWriteReleases>
                            <overWriteSnapshots>false</overWriteSnapshots>
                            <overWriteIfNewer>true</overWriteIfNewer>
                        </configuration>
                    </execution>

                    <execution>
                        <id>copy-dependencies</id>
                        <phase>package</phase>
                        <goals>
                            <goal>copy-dependencies</goal>
                        </goals>
                        <configuration>
                            <includeScope>compile</includeScope>
                            <outputDirectory>${project.build.directory}/libs</outputDirectory>
                        </configuration>
                    </execution>

                </executions>
            </plugin>

            <!-- JAR building -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <configuration>
                    <archive>
                        <manifest>
                            <addClasspath>true</addClasspath>
                            <classpathPrefix>libs/</classpathPrefix>
                            <classpathLayoutType>simple</classpathLayoutType>
                            <mainClass>com.vaadin.starter.skeleton.ManualJetty</mainClass>
                        </manifest>
                    </archive>
                    <includes>
                        <include>**/*.class</include>
                        <include>webapp/**/*</include>
                        <include>META-INF/**/*</include>
                    </includes>
                </configuration>
            </plugin>
```
then package will generate `libs` directory and a little starter JAR.

**Comment by mvysny** [comment]
Hi, thank you :+1: The uberjar approach has the advantage that it can be distributed and launched easily, since everything is contained within the jar itself. That being said, you're right that it's hard to see which dependencies went into it. There is also another hidden fault - in order to register multiple services onto one endpoint the Service API requires multiple files to be mapped to the same resource. However this is impossible with the uberjar approach since you have to pick one file.

I'm not entirely sure to remove uberjar yet though. I'm thinking of creating additional assembly output which zips the mini JAR and the libs directory side-by-side with the current uberjar.

**Comment by mvysny** [comment]
Hmm there seem to be a catch; the MANIFEST.MF/Class-Path seem to create a new ClassLoader which is ignored by Jetty; e.g. files from flow-client.jar/META-INF/resources are not served. I guess that's why you unpack `META-INF/resources/**/*,`, but that sounds a bit hackish to me. I'll try something else.

**Comment by mvysny** [comment]
I've created a zip file which includes a script which launches the entire app; I've updated the README to mention this zip file. Could you please pick up the newest master (or dc5980c8ccf492ac7a16e1ee73f6a6c66433a9e4 ) and try it out and provide a feedback please?

**Comment by lanmaster** [comment]
Will check now

**Comment by lanmaster** [comment]
If i start with `java -jar vaadin14-embedded-jetty-1.0-SNAPSHOT-uberjar.jar` then i have got an error:
```
[main] ERROR org.atmosphere.cpr.DefaultAsyncSupportResolver - Real error: Unable to configure jsr356 at that stage. ServerContainer is null
java.lang.IllegalStateException: Unable to configure jsr356 at that stage. ServerContainer is null
        at org.atmosphere.container.JSR356AsyncSupport.<init>(JSR356AsyncSupport.java:53)
        at org.atmosphere.container.JSR356AsyncSupport.<init>(JSR356AsyncSupport.java:42)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
```
but app is working. 
I add then `WebSocketServerContainerInitializer.initialize(context);` in ManualJetty.java after line
`context.addEventListener(new ServletContextListeners());`. Not sure it is very needed, but it removes error.

**Comment by lanmaster** [comment]
zip version also works fine!

**Comment by mvysny** [comment]
Thank you for the fix of `IllegalStateException: Unable to configure jsr356 at that stage.`, added to `ManualJetty.java`.

Thanks for confirming that the zip file works properly :) Closing as fixed.

**Comment by lanmaster** [comment]
> 
> 
> Hmm there seem to be a catch; the MANIFEST.MF/Class-Path seem to create a new ClassLoader which is ignored by Jetty; e.g. files from flow-client.jar/META-INF/resources are not served. I guess that's why you unpack `META-INF/resources/**/*,`, but that sounds a bit hackish to me. I'll try something else.

Maybe you know how to make Jetty to see static files from `flow-client.jar` without this hack?

**Comment by mvysny** [comment]
unfortunately I do not know that :(

And it's not just flow-client - other libraries can also publish their Polymer Templates, CSS or JavaScript files via `META-INF/resources/` (for example appreciated/app-layout-addon:4.0.0 jar), so I don't think handling `flow-client.jar` in a special way is a sound solution. 

The best way is to understand how that custom classloader works and why Jetty can't hook into it; maybe all that's needed is to set a proper classloader to Jetty... Perhaps all we need to do is to call `context.setClassLoader(Thread.currentThread().getContextClassLoader());` in ManualJetty.java...
