### ISSUE TITLE
Disable new AnnotationConfiguration()

### ISSUE THREAD

**Issue by lanmaster** [mvysny/vaadin14-embedded-jetty#6]
Using `AnnotationConfiguration` is unwanted in large applications, because it took large time on scan classes each restart. How can we disable AnnotationConfiguration() ?

**Comment by lanmaster** [comment]
There is Vaadin forum thread: [https://vaadin.com/forum/thread/17929998/routeconfiguration-and-route](https://vaadin.com/forum/thread/17929998/routeconfiguration-and-route)

**Comment by mvysny** [comment]
You can simply remove the `new AnnotationConfiguration()` from ManualJetty.java:36, but then you need to auto-discover the routes as a bare minimum. Unfortunately I don't have the time to do that myself, but you can perhaps inspire yourself from Karibu-Testing V10 route auto-discovery+registration code at https://github.com/mvysny/karibu-testing/blob/master/karibu-testing-v10/src/main/kotlin/com/github/mvysny/kaributesting/v10/BasicUtils.kt#L54 and https://github.com/mvysny/karibu-testing/blob/master/karibu-testing-v10/src/main/kotlin/com/github/mvysny/kaributesting/v10/BasicUtils.kt#L69

Note that you will probably need to initialize all classes implementing `ServletContainerInitializer` manually.

**Comment by lanmaster** [comment]
Thanks, Martin! Maybe i will try to translate Kotlin to Java later. This issue is not really relevant to the repo and it is closed.
