### ISSUE TITLE
Notification didn't appear

### ISSUE THREAD

**Issue by lanmaster** [mvysny/vaadin14-embedded-jetty#7]
There is no visual reaction on button click. Tested in latest Chrome.

**Comment by mvysny** [comment]
Hi, the notification appears in the lower left part of the screen. Could you check the app running at https://vaadin14-embedded-jetty.herokuapp.com/ whether the notification appears? It appears for me.

**Comment by lanmaster** [comment]
Hi! it appers for me too )
